name: Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: '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' # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'main'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: '/jekyll-theme-yat'  # Default is empty
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
      # Add a step to generate and move the Sitemap
      - name: Generate and move Sitemap
        run: |
          bundle exec jekyll build
          echo "Generated files:"
          ls -R _site
          mv _site/sitemap.xml sitemap.xml
        working-directory: ./  # Specify the working directory for this step
